
spring.application.name=hackhub-demo

#CONFIGURAZIONE DATABASE 
spring.datasource.url=jdbc:h2:mem:hackhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#INIZIALIZZAZIONE DATI
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#CONSOLE H2 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

#LOGGING
logging.level.org.springframework.security=DEBUG